### ISSUE TITLE
Docker image doesn't work in raspberry pi 3

### ISSUE THREAD

**Issue by alexppg** [squat/kilo#21]
Hi
I've seen this [commit](https://github.com/squat/kilo/commit/adb09ce6202a1a867b871bda3add212549bdaf3f) which adds support to arm architectures, but it doesn't work. It returns this:
```
no matching manifest for linux/arm/v7 in the manifest list entries
```
I'm doing anything wrong?

**Comment by squat** [comment]
@alexppg ah thanks for reporting that. I just added a commit that fixed support for arm64 (https://github.com/squat/kilo/commit/7c90a40c5a78b0feb411f8cc2b01be858ad733ea) and confirmed it worked. Now I think I need to make one more commit to fix regular arm that annotates the image with `v7`. I don’t have an arm host to test on. Can I build an image using a new commit and ask you to docker pull it to verify?

**Comment by alexppg** [comment]
Sure, I'll do it when you push it. Thanks!

**Comment by squat** [comment]
OK, plz try `docker pull squat/kilo:7c90a40c5a78b0feb411f8cc2b01be858ad733ea-dirty` from the arm device. If it works, then I'll push the commit and we can run the tags built by CI.

**Comment by alexppg** [comment]
It works \o/ Thanks! I even tried to run it and it worked perfectly.

**Comment by squat** [comment]
Awesome :))) I’ll push the commit then

**Comment by squat** [comment]
Fixed by https://github.com/squat/kilo/commit/f04944df4a9c63fee2bb582921e6b2b0482e25da
Please re-open if there are any more issues with the arm image

**Comment by alexppg** [comment]
I think there's still a problem. It doesn't find the reference that the manifest points:
```
Failed to pull image "squat/kilo": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/squat/kilo:latest": failed to unpack image on snapshotter overlayfs: no match for platform in manifest sha256:0773283ac5e910c593cae92ce78745446cb52073824915e22c97d9d3ed297f96: not found
```

**Comment by squat** [comment]
yes, you're totally right, building the container manifests for `squat/kilo:latest` is broken; it lists all of the images as type `amd64`. Pulling the manifests for `squat/kilo:<COMMIT>` should work as expected. Commit https://github.com/squat/kilo/commit/887806c7ce96853239fe137402486308512a7baf should now fix the generation of  `latest` manifests. Thanks for testing this on different archs!

**Comment by alexppg** [comment]
thank you for your work. it works now \o/
