### ISSUE TITLE
VPN only: failed to read CNI config list file

### ISSUE THREAD

**Issue by benosman** [squat/kilo#36]
Hello,

I am trying to set up a VPN only kilo installation on a Rancher RKE / Canal based cluster.

I ended up using the manifest suggested in #30, making sure it is set to go to a single node. It installs fine, and the kilo pod is running.

When I add a peer using the suggested manifest (filling in public key), the kilo pod has an error as follows:

```
{"caller":"main.go:217","msg":"Starting Kilo network mesh 'ba00b6c180d40bd73fc94af5be3bbf8f85789bf9'.","ts":"2020-02-22T20:54:17.234829806Z"}
{"caller":"cni.go:58","component":"kilo","err":"failed to read CNI config list file: error reading /etc/cni/net.d/10-kilo.conflist: open /etc/cni/net.d/10-kilo.conflist: no such file or directory","level":"warn","msg":"failed to get CIDR from CNI file; overwriting it","ts":"2020-02-22T20:54:17.336024857Z"}
{"caller":"cni.go:66","component":"kilo","level":"info","msg":"CIDR in CNI file is empty","ts":"2020-02-22T20:54:17.336108147Z"}
{"CIDR":"10.42.3.0/24","caller":"cni.go:71","component":"kilo","level":"info","msg":"setting CIDR in CNI file","ts":"2020-02-22T20:54:17.336140049Z"}
{"caller":"cni.go:73","component":"kilo","err":"failed to read CNI config list file: open /etc/cni/net.d/10-kilo.conflist: no such file or directory","level":"warn","msg":"failed to set CIDR in CNI file","ts":"2020-02-22T20:54:17.33616623Z"}
{"caller":"mesh.go:482","component":"kilo","event":"add","level":"info","peer":{"AllowedIPs":[{"IP":"10.5.0.1","Mask":"/////w=="}],"Endpoint":null,"PersistentKeepalive":10,"PublicKey":"<...>","Name":"squat"},"ts":"2020-02-22T20:54:17.486646157Z"}
{"caller":"mesh.go:717","component":"kilo","error":"failed to delete configuration file: remove /var/lib/kilo/conf: no such file or directory","level":"error","ts":"2020-02-22T20:54:17.486913746Z"}
{"caller":"mesh.go:727","component":"kilo","error":"failed to clean up node backend: failed to patch node: the server rejected our request due to an error in our request","level":"error","ts":"2020-02-22T20:54:17.493099325Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11f6048]
goroutine 31 [running]:
github.com/squat/kilo/pkg/mesh.(*Mesh).resolveEndpoints(0xc00023c580, 0x16, 0x0)
	/kilo/pkg/mesh/mesh.go:764 +0x2f8
github.com/squat/kilo/pkg/mesh.(*Mesh).applyTopology(0xc00023c580)
	/kilo/pkg/mesh/mesh.go:560 +0xc7
github.com/squat/kilo/pkg/mesh.(*Mesh).syncPeers(0xc00023c580, 0xc00035c060)
	/kilo/pkg/mesh/mesh.go:483 +0x51d
github.com/squat/kilo/pkg/mesh.(*Mesh).Run(0xc00023c580, 0x0, 0x0)
	/kilo/pkg/mesh/mesh.go:350 +0x632
main.Main.func4(0x0, 0x0)
	/kilo/cmd/kg/main.go:218 +0x14a
github.com/oklog/run.(*Group).Run.func1(0xc00049f740, 0xc0003a7ca0, 0xc0002aa860)
	/kilo/vendor/github.com/oklog/run/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
	/kilo/vendor/github.com/oklog/run/group.go:37 +0xbb
```

According to the manifest I am using, CNI is not enabled (`--cni=false`) but it is still looking for this file.  Any suggestions on how to get this working?

https://github.com/squat/kilo/blob/5a45c1f85b0ab2230961ecd652c76587b023b8d9/manifests/kilo-vpn-only-example.yaml

Thanks,

Ben

**Comment by benosman** [comment]
> From the looks of the error you shared, it seems that you removed the flag turning off CNI, otherwise Kilo would not be trying to set any CNI configuration. Please try adding `--cni=false`, as Flannel takes care of CNI for you when you are running Canal.

@squat : thanks for your above reply in the other issue. I've moved it here as the full error is listed. 

It was my first thought about the `--cni flag` but It is definitely inplace still in the manifest and even when checking the pod in the dashboard. 

![image](https://user-images.githubusercontent.com/305317/75099386-0934fe00-55b9-11ea-899d-1b207943b50f.png)

**Comment by squat** [comment]
hi @benosman yes you are completely right :) it looks like there are two issues. The first one is a segfault introduced by #35, this is not directly related to the issue of CNI, though it is in your logs. I just pushed a commit that fixes this.

The second issue is that it looks like Kilo erroneously tries to read the CNI config one time even if CNI is disabled. This will fail if you haven't provided a CNI config and normally Kilo will move on, however in your case you ran into the segfault. In any case, with the latest build from master (5 minutes ago) you should be able to make progress. I'll push a commit nonetheless to fix this behavior to ensure CNI is not touched erroneously.

**Comment by benosman** [comment]
@squat Thank you for your rapid response! :)

I've just pulled the latest image and it is as you say, I still get the warning, but you've fixed the segfault, so it carries on regardless.

Later on I'll actually get the peer set up correctly and give it a full test, but it looks good for now - many thanks! 👍

**Comment by squat** [comment]
I'm glad you were able to get going! I just pushed the commit fixing that CNI issue; the situation triggering the warning should no longer be encountered when CNI is disabled. Please let me know how it goes with the manifests in the PR. I am reviewing it and will hopefully merge it this week :)

**Comment by skurfuerst** [comment]
ah, so great you got it working ❤️
